default:
  image: "node:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  before_script:
    - apt update -y
    - apt install -y jq
  script:
    - ./manage.sh publish
  pages: # specifies that this is a Pages job
    publish: dist
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
